version: "3.5"

services:
  postgres-memefactory:
    container_name: postgres-memefactory
    image: postgres
    environment:
      POSTGRES_USER: memefactory
      POSTGRES_PASSWORD: 'memefactory123'
      POSTGRES_DB: memefactory
    expose:
    - 5432
    ports:
    - 5432:5432
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql